# 请根据自身需求修改
appname: DbyApp-prod
appversion: 1.0.0
debug: false
log_dir: ./log
is_disable_docs: true
# #
snow_worker_id: 0
snow_datacenter_id: 0
redis_host:
redis_port:
redis_db:
redis_password:
db_url: postgresql://<username>:<password>@<host>:<port>/app_prod
db_async_url: postgresql+asyncpg://<username>:<password>@<host>:<port>/app_prod
