# 请根据自身需求修改
appname: DbyApp-dev
appversion: 1.0.0
debug: true
log_dir: ./log
is_disable_docs: false
# #
snow_worker_id: 0
snow_datacenter_id: 0
redis_host: 111.229.104.99
redis_port: 6379
redis_db:
redis_password: Li123456
db_url: postgresql://root:Li123456@111.229.104.99:5432/app_dev
db_async_url: postgresql+asyncpg://root:Li123456@111.229.104.99:5432/app_dev
